//@/appadmin/manifest/bsData.ts
export type BsCategory =
  | "vision"
  | "spiritualite"
  | "culture"
  | "gouvernance"
  | "infrastructure"
  | "ecologie"
  | "economie"
  | "social"
  | "sante"
  | "dimensions";

export type BsStatus = "draft" | "ok" | "todo";

export type BsTag = {
  id: string; // slug stable pour URL/DB
  label: string; // texte affiché
  order: number; // obligatoire (tri)
  category: BsCategory; // classification
  definition: string; // court texte explicatif
  isTag: boolean; // si tu veux garder ce flag
  keywords: string[]; // recherche/synonymes
  related: string[]; // ids liés
  status?: BsStatus; // pour marquer ce qui reste à écrire
};

export const bstags = [
  {
    id: "agrimundo",
    label: "Identité",
    order: 0,
    category: "vision",
    definition:
      "Habitat collectif visant autonomie, entraide et stabilité financière. pas bio, pas vegan,mais utilisant les outils responsable pour assurer des profis dans le respect des ecosystème. intégrer a la vie sociale et economique du pays.ecologie pragmatique",
    isTag: true,
    status: "draft",
    keywords: [],
    related: [],
  },
  {
    id: "ecovillage",
    label: "Écovillage",
    order: 1,
    category: "vision",
    definition:
      "Habitat collectif visant autonomie, entraide et faible impact.",
    isTag: true,
    status: "draft",
    keywords: [],
    related: [],
  },
  {
    id: "spiritualité",
    label: "Spiritualité",
    order: 2,
    category: "culture",
    definition:
      "Référence initiatique/éthique (symboles, méthode, rituels). vivre en Chrétient ",
    isTag: true,
    status: "draft",
    keywords: ["symbolisme", "initiation"],
    related: [],
  },
  {
    id: "croyance-en-dieu",
    label: "Croyance en Dieu",
    order: 3,
    category: "spiritualite",
    definition: "Axe spirituel (foi, transcendance, sens).",
    isTag: true,
    status: "draft",
    keywords: [],
    related: [],
  },
  {
    id: "tradition",
    label: "Tradition",
    order: 4,
    category: "culture",
    definition: "Transmission de repères, rites, usages et mémoire collective.",
    isTag: true,
    status: "draft",
    keywords: [],
    related: [],
  },

  {
    id: "autonomie-energetique",
    label: "Autonomie énergétique",
    order: 5,
    category: "infrastructure",
    definition:
      "Production/stockage locaux (électricité, chaleur) et sobriété.",
    isTag: true,
    status: "draft",
    keywords: ["solaire", "stockage", "sobriete"],
    related: [],
  },
  {
    id: "travail-participatif",
    label: "Travail participatif",
    order: 6,
    category: "gouvernance",
    definition:
      "Organisation du travail commun (chantiers, rotations, règles).",
    isTag: true,
    status: "draft",
    keywords: [],
    related: [],
  },
  {
    id: "sel",
    label: "Système d’échange local (SEL)",
    order: 7,
    category: "economie",
    definition: "Échanges de biens/services via unité locale (temps/crédit).",
    isTag: true,
    status: "draft",
    keywords: ["monnaie locale", "entraide"],
    related: [],
  },
  {
    id: "symbolisme",
    label: "Symbolisme",
    order: 8,
    category: "culture",
    definition: "Langage de symboles pour relier pratique, valeurs et sens.",
    isTag: true,
    status: "draft",
    keywords: [],
    related: [],
  },

  {
    id: "dimension-physique",
    label: "Physique",
    order: 9,
    category: "dimensions",
    definition: "Santé du corps, activité, sommeil, sécurité matérielle.",
    isTag: true,
    status: "draft",
    keywords: [],
    related: [],
  },
  {
    id: "dimension-emotionnelle",
    label: "Émotionnelle",
    order: 10,
    category: "dimensions",
    definition: "Gestion des émotions, stabilité, empathie, apaisement.",
    isTag: true,
    status: "draft",
    keywords: [],
    related: [],
  },
  {
    id: "dimension-intellectuelle",
    label: "Intellectuelle",
    order: 11,
    category: "dimensions",
    definition: "Apprentissage, réflexion critique, transmission de savoirs.",
    isTag: true,
    status: "draft",
    keywords: [],
    related: [],
  },
  {
    id: "dimension-relationnelle",
    label: "Relationnelle",
    order: 12,
    category: "dimensions",
    definition: "Qualité des liens, coopération, médiation des conflits.",
    isTag: true,
    status: "draft",
    keywords: [],
    related: [],
  },
  {
    id: "dimension-sens",
    label: "Sens de la vie",
    order: 13,
    category: "dimensions",
    definition: "Orientation, vocation, finalités partagées et personnelles.",
    isTag: true,
    status: "draft",
    keywords: [],
    related: [],
  },
  {
    id: "dimension-action",
    label: "Action",
    order: 14,
    category: "dimensions",
    definition: "Passage à l’acte, projets, discipline, responsabilité.",
    isTag: true,
    status: "draft",
    keywords: [],
    related: [],
  },

  {
    id: "alimentation",
    label: "Alimentation",
    order: 15,
    category: "sante",
    definition: "Accès à une nourriture saine, locale et résiliente.",
    isTag: true,
    status: "draft",
    keywords: ["potager", "cuisine", "nutrition"],
    related: [],
  },
  {
    id: "habitation",
    label: "Habitation",
    order: 16,
    category: "infrastructure",
    definition: "Logements adaptés (confort, coût, matériaux, entretien).",
    isTag: true,
    status: "draft",
    keywords: [],
    related: [],
  },
  {
    id: "developpement-reproduction",
    label: "Développement (se reproduire)",
    order: 17,
    category: "social",
    definition: "Famille, enfance, continuité, soin et éducation.",
    isTag: true,
    status: "draft",
    keywords: ["enfance", "education"],
    related: [],
  },
  {
    id: "gestion-dechets",
    label: "Gestion des déchets",
    order: 18,
    category: "ecologie",
    definition: "Réduction, tri, compostage, filières et responsabilité.",
    isTag: true,
    status: "draft",
    keywords: [],
    related: ["recyclage"],
  },
  {
    id: "communiquer",
    label: "Communiquer",
    order: 19,
    category: "social",
    definition: "Communication claire, écoute, information interne.",
    isTag: true,
    status: "draft",
    keywords: [],
    related: [],
  },
  {
    id: "respirer",
    label: "Respirer",
    order: 20,
    category: "sante",
    definition: "Qualité de l’air, ventilation, activités, nature.",
    isTag: true,
    status: "draft",
    keywords: [],
    related: [],
  },

  {
    id: "identite",
    label: "Identité",
    order: 21,
    category: "vision",
    definition: "Qui sommes-nous ? Valeurs, récit commun, frontières.",
    isTag: true,
    status: "draft",
    keywords: [],
    related: [],
  },
  {
    id: "developpement-durable",
    label: "Développement durable",
    order: 22,
    category: "ecologie",
    definition: "Équilibre long terme entre humain, économie, écosystèmes.",
    isTag: true,
    status: "draft",
    keywords: [],
    related: [],
  },
  {
    id: "reseaux",
    label: "Réseaux",
    order: 23,
    category: "social",
    definition: "Partenariats, voisinage, entraide, réseaux pro/associatifs.",
    isTag: true,
    status: "draft",
    keywords: [],
    related: [],
  },
  {
    id: "integration-cite",
    label: "Intégration à la cité (vie politique)",
    order: 24,
    category: "gouvernance",
    definition: "Lien aux institutions, participation civique, droit local.",
    isTag: true,
    status: "draft",
    keywords: [],
    related: [],
  },

  {
    id: "locaux-communs",
    label: "Locaux communs",
    order: 25,
    category: "infrastructure",
    definition:
      "Espaces partagés (ateliers, cuisine, salle commune, stockage).",
    isTag: true,
    status: "draft",
    keywords: [],
    related: [],
  },
  {
    id: "habitat-individuel",
    label: "Habitat individuel",
    order: 26,
    category: "infrastructure",
    definition: "Part privée : intimité, règles d’usage, limites.",
    isTag: true,
    status: "draft",
    keywords: [],
    related: ["locaux-communs"],
  },

  {
    id: "produire-vendre",
    label: "Produire & vendre",
    order: 27,
    category: "economie",
    definition: "Activités productives, circuits courts, prix justes.",
    isTag: true,
    status: "draft",
    keywords: [],
    related: [],
  },
  {
    id: "gestion-energie",
    label: "Gestion des énergies",
    order: 28,
    category: "infrastructure",
    definition: "Eau, électricité, chaleur : pilotage, maintenance, sobriété.",
    isTag: true,
    status: "draft",
    keywords: ["eau", "electricite"],
    related: [],
  },
  {
    id: "gestion-financiere",
    label: "Gestion financière",
    order: 29,
    category: "economie",
    definition: "Budget collectif et individuel, transparence, règles.",
    isTag: true,
    status: "draft",
    keywords: [],
    related: [],
  },

  {
    id: "ceremonie",
    label: "Cérémonie",
    order: 30,
    category: "culture",
    definition: "Rituels civils/spirituels/communs pour marquer le temps.",
    isTag: true,
    status: "draft",
    keywords: [],
    related: [],
  },
  {
    id: "recyclage",
    label: "Recyclage",
    order: 31,
    category: "ecologie",
    definition: "Valorisation des matières via filières et réemploi.",
    isTag: true,
    status: "draft",
    keywords: [],
    related: [],
  },
  {
    id: "mise-en-commun",
    label: "Mise en commun des ressources",
    order: 32,
    category: "economie",
    definition: "Partage : vêtements, outils, moyens de production.",
    isTag: true,
    status: "draft",
    keywords: ["mutualisation"],
    related: [],
  },

  {
    id: "mixite",
    label: "Mixité",
    order: 33,
    category: "social",
    definition: "Diversité d’âges, d’origines, de profils et inclusion.",
    isTag: true,
    status: "draft",
    keywords: [],
    related: [],
  },
  {
    id: "valeurs-traditionnelles",
    label: "Valeurs traditionnelles",
    order: 34,
    category: "culture",
    definition:
      "Principes éthiques durables (responsabilité, respect, mesure).",
    isTag: true,
    status: "draft",
    keywords: [],
    related: [],
  },
  {
    id: "chants-taize",
    label: "Chants de Taizé",
    order: 35,
    category: "spiritualite",
    definition: "Chants méditatifs favorisant intériorité et cohésion.",
    isTag: true,
    status: "draft",
    keywords: [],
    related: [],
  },
  {
    id: "rituel-communautaire",
    label: "Rituels communautaires",
    order: 39,
    category: "spiritualite",
    definition:
      "reunions, chaînes d’union, agapes, ouvertures/fermetures pour rythmer temps collective.",
    isTag: true,
    status: "draft",
    keywords: ["tenue", "chaîne d’union", "agapes"],
    related: ["ceremonie", "chants-taize"],
  },
  {
    id: "agriculture",
    label: "Agriculture",
    order: 40,
    category: "ecologie",
    definition:
      "Méthodes qui augmentent la production en respectant les écosystèmes.",
    isTag: true,
    status: "draft",
    keywords: [
      "régénératif",
      "sol vivant",
      "permaculture",
      "agroécologie",
      "carbon farming",
    ],
    related: ["permaculture", "compostage", "biodiversite"],
  },
  {
    id: "resiliance",
    label: "Résiliance",
    order: 42,
    category: "ecologie",
    definition:
      "tendre vers l'autonomie energetique et alimentaire. habitation confortable et durable",
    isTag: true,
    status: "draft",
    keywords: [
      "autosuffisance alimentaire",
      "nourriture locale",
      "semences paysannes",
    ],
    related: ["alimentation", "potager", "produire-vendre"],
  },
] satisfies readonly BsTag[];
