//@/copmponents/layout/header/MainNavData.ts
export type Role = "public" | "user" | "client" | "pro" | "dev" | "admin";

export type NavItem = {
  id: string;
  label: string;
  href?: string | null;
  order: number;
  parentId?: string | null;
  allowedRoles: Role[];
  isVisible: boolean;
  children: NavItem[];
};

export const NAV_FLAT: Omit<NavItem, "children">[] = [
  {
    id: "home",
    label: "Home",
    href: "/",
    order: 1,
    parentId: null,
    allowedRoles: ["public"],
    isVisible: false,
  },

  {
    id: "cultures",
    label: "Cultures",
    href: "/public/cultures",
    order: 2,
    parentId: null,
    allowedRoles: ["public"],
    isVisible: true,
  },
  {
    id: "cultures-production",
    label: "Production",
    href: "/public/cultures/production",
    order: 1,
    parentId: "cultures",
    allowedRoles: ["public"],
    isVisible: true,
  },
  {
    id: "cultures-serre",
    label: "Serre",
    href: "/public/cultures/serre",
    order: 2,
    parentId: "cultures",
    allowedRoles: ["public"],
    isVisible: true,
  },
  {
    id: "cultures-hydro",
    label: "Hydroponie",
    href: "/public/cultures/hydroponie",
    order: 3,
    parentId: "cultures",
    allowedRoles: ["public"],
    isVisible: true,
  },
  {
    id: "cultures-micro",
    label: "Micropousses",
    href: "/public/cultures/micropousses",
    order: 4,
    parentId: "cultures",
    allowedRoles: ["public"],
    isVisible: true,
  },

  {
    id: "myco",
    label: "Champignon",
    href: "/public/mycoculture",
    order: 3,
    parentId: null,
    allowedRoles: ["public"],
    isVisible: true,
  },
  {
    id: "myco-guide",
    label: "Guide de Culture",
    href: "/public/mycoculture/guideMycoculture",
    order: 1,
    parentId: "myco",
    allowedRoles: ["public"],
    isVisible: true,
  },
  {
    id: "myco-gloss",
    label: "Glossaire",
    href: "/public/mycoculture/glossary",
    order: 2,
    parentId: "myco",
    allowedRoles: ["public"],
    isVisible: true,
  },

  {
    id: "aqua",
    label: "Aquaponie",
    href: "/public/aquaponie",
    order: 4,
    parentId: null,
    allowedRoles: ["public"],
    isVisible: true,
  },
  {
    id: "aqua-guide",
    label: "Guide de Culture",
    href: "/public/aquaponie/guideAquaponie",
    order: 1,
    parentId: "aqua",
    allowedRoles: ["public"],
    isVisible: true,
  },
  {
    id: "aqua-gloss",
    label: "Glossaire",
    href: "/public/aquaponie/glossary",
    order: 2,
    parentId: "aqua",
    allowedRoles: ["public"],
    isVisible: true,
  },

  {
    id: "api",
    label: "Apiculture",
    href: "/public/apiculture",
    order: 5,
    parentId: null,
    allowedRoles: ["public"],
    isVisible: true,
  },
  {
    id: "api-guide",
    label: "Guide de Production",
    href: "/public/apiculture",
    order: 1,
    parentId: "api",
    allowedRoles: ["public"],
    isVisible: true,
  },
  {
    id: "api-gloss",
    label: "Glossaire",
    href: "/public/apiculture/glossary",
    order: 2,
    parentId: "api",
    allowedRoles: ["public"],
    isVisible: true,
  },

  {
    id: "avi",
    label: "Aviculture",
    href: "/public/aviculture",
    order: 6,
    parentId: null,
    allowedRoles: ["public"],
    isVisible: true,
  },
  {
    id: "avi-guide",
    label: "Guide d'Elevage",
    href: "/public/aviculture",
    order: 1,
    parentId: "avi",
    allowedRoles: ["public"],
    isVisible: true,
  },
  {
    id: "avi-admin",
    label: "Admin",
    href: "/public/aviculture/admin",
    order: 2,
    parentId: "avi",
    allowedRoles: ["admin", "dev"],
    isVisible: true,
  },
  {
    id: "avi-gloss",
    label: "Glossaire",
    href: "/public/aviculture/glossary",
    order: 3,
    parentId: "avi",
    allowedRoles: ["public"],
    isVisible: true,
  },

  {
    id: "bsf",
    label: "BSF",
    href: "/public/bsf",
    order: 7,
    parentId: null,
    allowedRoles: ["public"],
    isVisible: true,
  },
  {
    id: "bsf-guide",
    label: "Guide de Production",
    href: "/public/bsf/guideBsf",
    order: 1,
    parentId: "bsf",
    allowedRoles: ["public"],
    isVisible: true,
  },
  {
    id: "bsf-gloss",
    label: "Glossaire",
    href: "/public/bsf/glossary",
    order: 2,
    parentId: "bsf",
    allowedRoles: ["public"],
    isVisible: true,
  },

  {
    id: "recettes",
    label: "Recettes",
    href: "/public/recettes",
    order: 8,
    parentId: null,
    allowedRoles: ["public"],
    isVisible: true,
  },
  {
    id: "recettes-list",
    label: "Liste des recettes",
    href: "/public/recettes",
    order: 1,
    parentId: "recettes",
    allowedRoles: ["public"],
    isVisible: true,
  },

  {
    id: "compliance",
    label: "Réglementations",
    href: "/public/compliance",
    order: 9,
    parentId: null,
    allowedRoles: ["public"],
    isVisible: true,
  },
  {
    id: "compliance-guide",
    label: "Guide",
    href: "/public/compliance",
    order: 1,
    parentId: "compliance",
    allowedRoles: ["public"],
    isVisible: true,
  },

  {
    id: "pro",
    label: "Business / Pro",
    href: "/pro",
    order: 10,
    parentId: null,
    allowedRoles: ["public", "pro", "admin"],
    isVisible: true,
  },
  {
    id: "pro-dashboard",
    label: "Tableau de bord",
    href: "/pro/dashboard",
    order: 1,
    parentId: "pro",
    allowedRoles: ["public", "pro", "admin"],
    isVisible: true,
  },
  {
    id: "pro-organisation",
    label: "Organisation",
    href: "/pro/organisation",
    order: 2,
    parentId: "pro",
    allowedRoles: ["public", "pro", "admin"],
    isVisible: true,
  },
  {
    id: "pro-produit",
    label: "Produit",
    href: "/pro/produit",
    order: 3,
    parentId: "pro",
    allowedRoles: ["public", "pro", "admin"],
    isVisible: true,
  },
  {
    id: "pro-client",
    label: "Client",
    href: "/pro/client",
    order: 4,
    parentId: "pro",
    allowedRoles: ["public", "pro", "admin"],
    isVisible: true,
  },
  {
    id: "pro-vente",
    label: "Ventes",
    href: "/pro/vente",
    order: 5,
    parentId: "pro",
    allowedRoles: ["public", "pro", "admin"],
    isVisible: true,
  },
  {
    id: "pro-apro",
    label: "Approvisionnement",
    href: "/pro/aprovisonement",
    order: 6,
    parentId: "pro",
    allowedRoles: ["public", "pro", "admin"],
    isVisible: true,
  },
  {
    id: "pro-stock",
    label: "Stocks",
    href: "/pro/stock",
    order: 7,
    parentId: "pro",
    allowedRoles: ["public", "pro", "admin"],
    isVisible: true,
  },

  {
    id: "dev",
    label: "Dev",
    href: "/dev",
    order: 11,
    parentId: null,
    allowedRoles: ["public", "dev", "admin"],
    isVisible: true,
  },
  {
    id: "dev-feature",
    label: "feature",
    href: "/dev/feature",
    order: 1,
    parentId: "dev",
    allowedRoles: ["public", "dev", "admin"],
    isVisible: true,
  },
  {
    id: "dev-schema",
    label: "Schema DB",
    href: "/dev/schema",
    order: 2,
    parentId: "dev",
    allowedRoles: ["public", "dev", "admin"],
    isVisible: true,
  },
  {
    id: "dev-tools",
    label: "Tools",
    href: "/dev/tools",
    order: 3,
    parentId: "dev",
    allowedRoles: ["public", "dev", "admin"],
    isVisible: true,
  },

  {
    id: "admin",
    label: "Admin",
    href: "/admin",
    order: 12,
    parentId: null,
    allowedRoles: ["public", "admin"],
    isVisible: true,
  },
  {
    id: "admin-manifest",
    label: "Brain Storming Manifest",
    href: "/admin/manifest",
    order: 1,
    parentId: "admin",
    allowedRoles: ["public", "admin"],
    isVisible: true,
  },
];
